name: BUILD EMACS AARCH64

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        include:
          - { host: x86_64, target: aarch64 }
          - { host: x86_64-musl, target: aarch64-musl }
    runs-on: ubuntu-22.04

    steps:
      - name: FREE DISK SPACE
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache/
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo docker image prune --all --force

      - name: CHECKOUT FORK
        uses: actions/checkout@v4
        with:
          path: void-packages

      - name: PREPARE XBPS-STATIC
        run: |
          mkdir -p /opt/xbps
          curl -LO http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz -C /opt/xbps
          rm xbps-static-latest.x86_64-musl.tar.xz

      - name: BUILD EMACS
        env:
          XBPS_TARGET_ARCH: ${{ matrix.target }}
        working-directory: void-packages
        run: |
          export PATH="/opt/xbps/usr/bin/:$PATH"
          ls
          if [[ "${{ matrix.host }}" == "${{ matrix.target }}" ]]; then
            ./xbps-src -A ${{ matrix.host }} binary-bootstrap
            ./xbps-src pkg -j4 -A ${{ matrix.host }} ~nativecomp emacs
          else
            ./xbps-src -a ${{ matrix.target }} -A ${{ matrix.host }} binary-bootstrap
            ./xbps-src pkg -j4 -a ${{ matrix.target }} -A ${{ matrix.host }} ~nativecomp emacs
          fi

      - name: SIGN
        env:
          XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
          XBPS_TARGET_ARCH: ${{ secrets.target }}
        working-directory: void-packages/hostdir/binpkgs
        run: |
          mkdir -p final_repo
          cp */*.xbps final_repo/
          cd final_repo
          #xbps-rindex -a *.xbps
          xbps-rindex -r $PWD
          xbps-rindex -s --signedby "${{ vars.SIGNEDBY }}" --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") .
          xbps-rindex -S --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") *.xbps
          xbps-rindex -c $PWD

      - name: CHECKSUM
        working-directory: void-packages/hostdir/binpkgs/final_repo/
        run: |
          sha256sum $(echo *.xbps)
          sha512sum $(echo *.xbps)

      - name: RELEASE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: emacs-aarch64-${{ github.sha }}
          files: |
            void-packages/hostdir/binpkgs/final_repo/*
